name: Manual Build Ladybird

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Chocolatey
      run: |
        curl -o install.ps1 -L https://chocolatey.org/install.ps1
        cmd /c powershell -ExecutionPolicy Bypass -File install.ps1

    - name: Install dependencies
      run: |
        choco install -y mingw cmake llvm ninja

    - name: Install simdutf
      run: |
        git clone https://github.com/simdutf/simdutf.git
        cd simdutf
        mkdir build
        cd build
        cmake .. -DSIMDUTF_BUILD_BENCHMARKS=OFF
        cmake --build .
        if (!(Test-Path "D:\a\ladybird\ladybird\simdutf\build\tools\Release\sutf.exe")) { cmake --install . }

    - name: Configure CMake
      run: cmake -GNinja -BBuild/release

    - name: Build with Ninja
      run: ninja -CBuild/release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: Build/release/
