name: Manual Build Ladybird

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf autoconf-archive automake build-essential ccache cmake curl fonts-liberation2 git libgl1-mesa-dev nasm ninja-build pkg-config qt6-base-dev qt6-tools-dev-tools qt6-wayland tar unzip zip libpulse-dev g++-13

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install autoconf autoconf-archive automake ccache cmake nasm ninja pkg-config llvm@18 qt

    - name: Install Chocolatey on Windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        choco install -y mingw cmake llvm ninja

    - name: Configure CMake
      run: cmake -GNinja -BBuild/release

    - name: Build with Ninja
      run: ninja -CBuild/release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: Build/release/
