name: Build Ladybird

on:
  workflow_dispatch:
  

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y autoconf autoconf-archive automake build-essential ccache cmake curl fonts-liberation2 git libgl1-mesa-dev nasm ninja-build pkg-config qt6-base-dev qt6-tools-dev-tools qt6-wayland tar unzip zip
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install -y g++-13
          cmake --version
      - name: Install GCC 12
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install gcc-12 g++-12 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
          gcc --version

      - name: Install simdutf
        run: |
          git clone https://github.com/simdutf/simdutf.git
          cd simdutf
          cmake -Bbuild -H.
          sudo cmake --install build --prefix /usr/local

      - name: Build Ladybird
        run: |
          cmake -GNinja -B Build/release
          ninja -C Build/release

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf autoconf-archive automake ccache cmake nasm ninja pkg-config qt
          cmake -GNinja -B Build/release
          ninja -C Build/release

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up WSL2
        run: |
          wsl --install -d Ubuntu
          wsl -e sudo apt update
          wsl -e sudo apt install -y autoconf autoconf-archive automake build-essential ccache cmake curl fonts-liberation2 git libgl1-mesa-dev nasm ninja-build pkg-config qt6-base-dev qt6-tools-dev-tools qt6-wayland tar unzip zip
          wsl -e sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          wsl -e sudo apt update
          wsl -e sudo apt install -y g++-13

      - name: Build Ladybird
        run: |
          wsl -e cmake -GNinja -B Build/release
          wsl -e ninja -C Build/release
